src/detail/element_difference.cpp, test/string_test.cpp
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/3)
=> Fixed locale output.

CMakeLists.txt, cmake/Modules/cotire.cmake
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/6)
=> Added cotire to build scripts.

.travis.yml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/7)
=> Added compilation of unity builds to Travis.

test/terminal_string_test.cpp
Closes #12
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/13)
=> 12 string tests

CMakeLists.txt, include/terminalpp/canvas.hpp, src/canvas.cpp, src/extent.cpp, test/canvas_test.cpp
Closes #11.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/19)
=> Canvas object#11

.travis.yml
Closes #11.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/20)
=> Added slack integration to Travis.

CMakeLists.txt, README.md, include/terminalpp/screen.hpp, src/screen.cpp, test/screen_test.cpp
This can be used to store up changes and batch them all together in
one draw operation, using a terminal.
Closes #15.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/21)
=> Added a Screen object.

.travis.yml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/26)
=> New cmake location

CMakeLists.txt
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/28)
=> Allow policy setting to work on earlier cmake versions.

CMakeLists.txt, include/terminalpp/ansi/control_sequence.hpp, include/terminalpp/ansi/mouse.hpp, include/terminalpp/virtual_key.hpp, test/expect_tokens.cpp
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/31)
=> Filled in the missing symbols from the latest features.

CMakeLists.txt, include/terminalpp/ansi/dec_private_mode.hpp, include/terminalpp/terminal.hpp, src/terminal.cpp, test/terminal_settings_test.cpp
Closes #29
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/32)
=> Enable mouse tracking#29

include/terminalpp/ansi/osc.hpp, include/terminalpp/detail/terminal_control.hpp, include/terminalpp/terminal.hpp, src/detail/terminal_control.cpp, src/terminal.cpp, test/terminal_settings_test.cpp
Closes #30.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/33)
=> Added support for setting the window title.

CMakeLists.txt, include/terminalpp/detail/well_known_virtual_key.hpp, src/detail/well_known_virtual_key.cpp, src/terminal.cpp
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/34)
=> Refactored virtual key handling logic out of Terminal.

include/terminalpp/attribute.hpp, include/terminalpp/glyph.hpp, include/terminalpp/point.hpp, include/terminalpp/virtual_key.hpp
Closes #42
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/43)
=> Exported symbols, filled in some comments.

CMakeLists.txt, include/terminalpp/element.hpp, test/canvas_test.cpp, test/element_test.cpp
Closes #38
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/44)
=> Allow implicit initialization of element from char.

include/terminalpp/terminalpp.hpp
Closes #37
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/45)
=> Added a convenience header.

CMakeLists.txt, include/terminalpp/string.hpp, src/string.cpp, test/element_test.cpp, test/string_test.cpp
Applies attribute to all elements.  Closes #41
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/46)
=> Added std::string/attr initializer for string.

CMakeLists.txt, include/terminalpp/attribute.hpp, src/attribute.cpp, test/colour_test.cpp
Closes #40
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/47)
=> Added constructor from colour enum to colour.

include/terminalpp/string.hpp, src/encoder.cpp, src/string.cpp, test/string_test.cpp
Closes #39
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/48)
=> Can now convert from terminal to std strings.

include/terminalpp/ansi/mouse.hpp, src/detail/parse_helper.cpp, test/terminal_read_test.cpp
Closes #49
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/53)
=> Fixed off-by-one error when parsing mouse co-ordinates.

include/terminalpp/screen.hpp, src/screen.cpp, test/screen_test.cpp
Closes #55.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/57)
=> Modified screen to take extra canvas parameters in draw().

include/terminalpp/terminal.hpp, src/screen.cpp, src/terminal.cpp, test/screen_test.cpp, test/terminal_string_test.cpp
Closes #56
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/58)
=> Can now write single element with terminal.

CMakeLists.txt, include/terminalpp/virtual_key.hpp, test/virtual_key_test.cpp
Closes #62
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/65)
=> Added operators &, &=, and |= to vk_modifier.

include/terminalpp/ansi/mouse.hpp
Closes #61
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/66)
=> Updated constants in mouse header for scroll wheels and motion.

include/terminalpp/virtual_key.hpp, src/detail/well_known_virtual_key.cpp, test/terminal_read_cursor_test.cpp
Closes #60
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/67)
=> Directional and tab/reverse tab commands now have repeat counts.

src/detail/well_known_virtual_key.cpp, test/terminal_read_cursor_test.cpp, test/terminal_read_fkey_test.cpp
Closes #63
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/68)
=> Added meta-command handling to all cursor movement and f-keys.

CMakeLists.txt, include/terminalpp/canvas_view.hpp, src/canvas_view.cpp, test/canvas_view_test.cpp
Closes #18.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/70)
=> Implemented an offsettable view into a canvas.

.travis.yml, src/terminal.cpp, test/expect_sequence.cpp, test/screen_test.cpp
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/77)
=> Allow Travis to test with g++ 5.2

src/detail/well_known_virtual_key.cpp
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/82)
=> Minor optimization of well_known_virtual_key process.

include/terminalpp/terminalpp.hpp
Closes #78.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/83)
=> Added encoder.hpp to convenience header.

include/terminalpp/attribute.hpp, src/detail/element_difference.cpp, src/encoder.cpp, src/screen.cpp
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/84)
=> Smaller attributes

.travis.yml, CMakeLists.txt
Closes #98
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/99)
=> No longer generate hidden symbols for static libraries

.travis.yml, README.md
* Added integration from Travis.
* Added badge from Readme
Closes #96
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/101)
=> Added Gitter integration

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/102)
=> Added Forkability badge to Readme

src/canvas.cpp, src/encoder.cpp, src/string.cpp, src/virtual_key.cpp
* fixed some banner comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/105)
=> Minor editorial changes

include/terminalpp/detail/element_difference.hpp, include/terminalpp/terminal.hpp, src/detail/element_difference.cpp, src/terminal.cpp, test/terminal_string_test.cpp
Closes #107
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/108)
=> Unicode charset#107

include/terminalpp/ansi/control_sequence.hpp, include/terminalpp/detail/parser.hpp, src/detail/parser.cpp, test/terminal_read_test.cpp
Closes #109
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/111)
=> Extend command sequence#109

include/terminalpp/ansi/charset.hpp, include/terminalpp/ansi/control_characters.hpp, include/terminalpp/ansi/control_sequence.hpp, include/terminalpp/ansi/csi.hpp, include/terminalpp/ansi/dec_private_mode.hpp, include/terminalpp/ansi/graphics.hpp, include/terminalpp/ansi/mouse.hpp, include/terminalpp/ansi/osc.hpp, include/terminalpp/ansi/protocol.hpp, include/terminalpp/ansi/ss3.hpp, include/terminalpp/detail/ascii.hpp
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/116)
=> Documentation#106

CMakeLists.txt
Closes #113
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/115)
=> Changed doc target to telnetpp_doc.

include/terminalpp/ansi/graphics.hpp, include/terminalpp/ansi/mouse.hpp, include/terminalpp/attribute.hpp, include/terminalpp/canvas_view.hpp, include/terminalpp/terminal.hpp, src/encoder.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/118)
=> Further improvements to automatically-generated documentation

include/terminalpp/ansi/mouse.hpp, include/terminalpp/attribute.hpp
Closes #106
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/119)
=> Fixed mangled \brief documentation comments.

include/terminalpp/ansi/charset.hpp, include/terminalpp/ansi/csi.hpp, src/ansi/charset.cpp
Any further additions should be added as required.
Closes #114
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/120)
=> Escape codes#114

include/terminalpp/attribute.hpp, src/attribute.cpp, test/colour_test.cpp
Closes #89.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/121)
=> Better debug strings#89

CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/123)
=> Bump to version 1.2

src/encoder.cpp
Closes #124
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/126)
=> Added trailing NUL to extended charset encoding code.

.travis.yml, CMakeLists.txt
Closes #125
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/127)
=> Sanitizers#125

CMakeLists.txt, src/extent.cpp, test/extent_test.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/130)
=> Added test for extent's operator<<

.travis.yml, include/terminalpp/detail/lambda_visitor.hpp, src/detail/well_known_virtual_key.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/134)
=> Introduced lambda_visitor, applied to well-known-virtual-key

.travis.yml
Closes #135
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/136)
=> Upgraded to lcov 1.13

.travis.yml
Fixes #137
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/138)
=> Fixed lcov remove expression for test files.

CMakeLists.txt
Closes #140
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/141)
=> Added export of cmake config file

CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/145)
=> Bumped version to 1.2.1

CMakeLists.txt, src/ansi/control_sequence.cpp, src/detail/parser.cpp, src/detail/well_known_virtual_key.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/150)
=> Better project generation

CMakeLists.txt, include/terminalpp/glyph.hpp, src/encoder.cpp, test/glyph_test.cpp
Closes #149
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/151)
=> Added equality checks for unicode glyphs

include/terminalpp/ansi/dec_private_mode.hpp, include/terminalpp/default_terminal.hpp, include/terminalpp/terminal.hpp, src/default_terminal.cpp, test/default_terminal_settings_test.cpp
Closes #152 
Closes #153
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/154)
=> Alternate screen buffer#152#153

include/terminalpp/detail/lambda_visitor.hpp
Closes #148
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/159)
=> Added forwarding references to the lambda visitors.

test/virtual_key_test.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/171)
=> Include of missing tuple header in test.

CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/173)
=> Again, fixed the export/install properties of CMakeLists.txt

.travis.yml
The sanitizer itself has started crashing inexplicably.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/178)
=> Temporarily removed Address Sanitizer from Travis

include/terminalpp/ansi/charset.hpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/177)
=> Fix OSX build

.travis.yml, CHANGELOG.md, CMakeLists.txt, README.md, conanfile.py, test_package/CMakeLists.txt, test_package/conanfile.py, test_package/example.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/192)
=> Use Conan to manage dependencies

conanfile.py
From 2.0.0 to 1.3.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/194)
=> Corrected conan package version

conanfile.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/195)
=> Ensure that Conan packages also contain the versioned shared objects.

conanfile.py
Reduced exports size from nearly 3MB to 93KB.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/198)
=> Simplified Conan exports.

include/terminalpp/algorithm/for_each_in_region.hpp, include/terminalpp/canvas.hpp, include/terminalpp/rectangle.hpp, src/canvas.cpp, src/screen.cpp
Closes #201
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/202)
=> Added an algorithm to iterate over regions on the canvas.

include/terminalpp/string.hpp, src/string.cpp
Fixes #204
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/206)
=> Updated string to use size_type consistently.

include/terminalpp/point.hpp, test/point_test.cpp
Used the Boost.Operators mechanism to implement it.  Also refactored
existing +,- operators to work in terms of that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/207)
=> Implemented relational operators for Point.

include/terminalpp/ansi_terminal.hpp, include/terminalpp/behaviour.hpp, include/terminalpp/detail/terminal_cursor_control.hpp, include/terminalpp/terminal.hpp, src/ansi_terminal.cpp, src/detail/terminal_cursor_control.cpp, test/ansi_terminal_cursor_test.cpp
Closes #175
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/216)
=> One axis cursor movement#175

CMakeLists.txt, include/terminalpp/rectangle.hpp, src/rectangle.cpp, test/rectangle_test.cpp
Closes #217
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/222)
=> Implemented streaming output operator for Rectangle

CMakeLists.txt, conanfile.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/223)
=> Updated versions to 1.3.4

.travis.yml, conanfile.py
Also implemented a number of improvements in the CI script:
* Coverage and Sanitize are now options in Conan, and are forwarded as such in the Travis script.
* Anonymized the Travis tokens for Gitter and Slack (after disabling the old tokens).
* Fixed a couple of Travis build config warnings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/224)
=> Fix Travis coverage

README.md, examples/encoded_hello_world/CMakeLists.txt, examples/encoded_hello_world/README.md, examples/encoded_hello_world/conanfile.txt, examples/encoded_hello_world/src/encoded_hello_world.cpp, examples/hello_world/CMakeLists.txt, examples/hello_world/README.md, examples/hello_world/conanfile.txt, examples/hello_world/src/hello_world.cpp, examples/positioned_smiley/CMakeLists.txt, examples/positioned_smiley/README.md, examples/positioned_smiley/conanfile.txt, examples/positioned_smiley/src/positioned_smiley.cpp, examples/shocking_pink/CMakeLists.txt, examples/shocking_pink/README.md, examples/shocking_pink/conanfile.txt, examples/shocking_pink/src/shocking_pink.cpp, examples/tprint/CMakeLists.txt, examples/tprint/README.md, examples/tprint/conanfile.txt, examples/tprint/src/tprint.cpp
Added several example projects to showcase basic functionality of Terminal++.  These are linked to from the Readme, which has also been updated with code from more recent developments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/225)
=> Better installation docs#206

src/detail/well_known_virtual_key.cpp, test/virtual_key_test.cpp
Closes #226
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/227)
=> Add control sequence handler for End key.

include/terminalpp/detail/element_difference.hpp, include/terminalpp/detail/terminal_cursor_control.hpp
Closes #228
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/229)
=> Correct class forward declarations to struct where appropriate.

CMakeLists.txt, conanfile.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/230)
=> Updated to version 1.3.5

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/231)
=> Added C++ syntax highlighting to code blocks

.travis.yml, CMakeLists.txt, conanfile.py, src/colour.cpp, src/encoder.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/232)
=> Moved dependencies from bincrafters to conan center.

.appveyor.yml, include/terminalpp/attribute.hpp, include/terminalpp/behaviour.hpp, include/terminalpp/canvas.hpp, include/terminalpp/character_set.hpp, include/terminalpp/colour.hpp, include/terminalpp/element.hpp, include/terminalpp/extent.hpp, include/terminalpp/glyph.hpp, include/terminalpp/point.hpp, include/terminalpp/rectangle.hpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/249)
=> Terminal++ can now be built as a shared library on MSVC

CMakeLists.txt, cmake/terminalpp-config.cmake.in
Updated CMakeLists.txt to include better installation CMake scripts, loosely based on some examples used in dependant libraries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/251)
=> Updated installation guides in CMake scripts

.github/workflows/build.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/253)
=> Boost package in CI has changed name

include/terminalpp/point.hpp, include/terminalpp/rectangle.hpp, include/terminalpp/terminal.hpp, include/terminalpp/terminal_state.hpp, include/terminalpp/virtual_key.hpp
Closes #256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/258)
=> Corrected errors in document generation.

CMakeLists.txt
Fixes #260
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/261)
=> Declared libfmt as a public dependency

CMakeLists.txt, examples/encoded_hello_world/CMakeLists.txt, examples/hello_world/CMakeLists.txt, examples/positioned_smiley/CMakeLists.txt, examples/shocking_pink/CMakeLists.txt, examples/tprint/CMakeLists.txt
Also minor improvements to CMake scripts, including the addition of the d postfix for debug libraries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/262)
=> Namespaced library under KazDragon::.

README.md, examples/encoded_hello_world/README.md, examples/hello_world/README.md, examples/positioned_smiley/README.md, examples/shocking_pink/README.md, examples/tprint/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/271)
=> Updated project for package move from bintray to artifactory.

.gitignore, src/detail/well_known_virtual_key.cpp, test/terminal_read_test.cpp
Closes #279
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/280)
=> Added handling of modifiers for control sequences.

include/terminalpp/virtual_key.hpp, src/virtual_key.cpp, test/virtual_key_test.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/281)
=> Implemented is_control_key.

examples/colour_viewer/CMakeLists.txt, examples/colour_viewer/conanfile.txt, examples/colour_viewer/src/colour_viewer.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/287)
=> Added an example program to view colours

.github/workflows/build.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/294)
=> Added verification of conan create in CI scripts.

README.md, examples/shocking_pink/src/shocking_pink.cpp, include/terminalpp/screen.hpp, src/screen.cpp, test/screen_test.cpp
Closes #295
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/296)
=> Screen is now constructed directly with the terminal it operates on.

.github/workflows/build.yml, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/299)
=> More accurate coverage

.github/workflows/build.yml, include/terminalpp/attribute.hpp, include/terminalpp/detail/element_difference.hpp, include/terminalpp/point.hpp, src/control_sequence.cpp, src/manip/cursor.cpp, src/virtual_key.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/300)
=> Minor improvements to coverage

.ci/fetch_system_dependencies.sh, CMakeLists.txt, conanfile.py, test/element_udl_test.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/302)
=> Terminal++ requires gsl-lite 0.38

.ci/fetch_system_dependencies.sh, .github/workflows/build.yml, CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/303)
=> Install libfmt from apt

include/terminalpp/detail/element_difference.hpp, include/terminalpp/effect.hpp, test/terminal_string_test.cpp
Closes #306
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/KazDragon/terminalpp/307)
=> Transitions between faint and bold go through normal

.appveyor.yml, src/control_sequence.cpp, test/control_sequence_test.cpp
This reduces compile time slightly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/KazDragon/terminalpp/310)
=> Removed dependency on boost.spirit
