src/terminal.cpp, test/terminal_cursor_test.cpp
Now takes into account that functions involving ANSI co-ordinates are
1-based whereas most other operations are 0-based.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/59)
=> Fixed off-by-one errors in terminal cursor movement

test/terminal_read_cursor_test.cpp, test/terminal_read_fkey_test.cpp
It turns out it was already accidentally implemented when
implementing this on function keys.  These tests should now
keep them from accidentally becoming unimplemented.
Closes #64
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/69)
=> Added tests for home/end, etc. with modifiers.

src/encoder.cpp, test/encoder_test.cpp
Closes #72
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/74)
=> After \x, parser state is now correct.

include/terminalpp/ansi/protocol.hpp
ss3::HOME and ss3::END are already present as ss3::CURSOR_HOME and
ss3::CURSOR_END in ss3.hpp.  These appear to have been left over.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/103)
=> Removed ss3 commands from protocol.hpp

include/terminalpp/core.hpp
With some library/compiler combinations, including a standard library
causes a clash with max_align_t, which is only present in cstddef. This
minor change helps avoid that situation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/146)
=> Included cstddef in core.hpp

.gitignore, .travis.yml, CMakeLists.txt, LICENSE, include/terminalpp/version.hpp.in
Updated license to include real name and current date.
Terminal++ is now properly versioned when installing.  Fixes #164
Added a version header file. Fixes #155
Added a packaging script.  Fixes #157
Update Travis script to build with Trusty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/165)
=> Package trusty version

src/detail/terminal_cursor_control.cpp, test/ansi_terminal_cursor_test.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/176)
=> Fix redundant coordinates when moving cursor to home (#174)

include/terminalpp/string.hpp, src/string.cpp, test/string_test.cpp
o Can construct a string of a given length filled with copies of a
prototype element.
Closes #179
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/181)
=> Added new constructor for terminalpp::string

include/terminalpp/canvas_view.hpp, src/canvas_view.cpp
This means that it produces debug messages identical to the
element that it contains when being tested.
Closes #183
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/184)
=> Added an output operator to canvas_view::row_proxy

test/attribute_test.cpp
Fixes #196
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/197)
=> Changed to default constructor in test due to ambiguity revealed by gcc 7

CMakeLists.txt, conanfile.py, src/detail/element_difference.cpp, test/expect_sequence.cpp
In tests, changing out Boost.Format for usage of fmtlib reduced the impact of element_difference from 26% to 18%, with the string parsing (that isn't inlined) now taking only 14% of the time to change attributes.
Closes #199 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/200)
=> Replaced uses of Boost.Format with fmtlib.

CMakeLists.txt, conanfile.py, include/terminalpp/ansi_terminal.hpp, include/terminalpp/detail/element_difference.hpp, src/ansi_terminal.cpp, src/detail/element_difference.cpp, test/ansi_terminal_string_test.cpp, test/manip_test.cpp, test/screen_test.cpp
This ensures that drawing on a terminal that has, for example, an attribute
set from a previous application will no longer bleed that attribute until
the first non-default attribute is seen.
Fixed #185
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/203)
=> A terminal now explicitly sets the default attribute before writing any text.

.travis.yml
Reduces build time on Travis by about a third due to not having to download all Conan packages each time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/213)
=> Fix Travis cache

CMakeLists.txt, include/terminalpp/attribute.hpp, include/terminalpp/character_set.hpp, include/terminalpp/colour.hpp, include/terminalpp/detail/lambda_visitor.hpp, include/terminalpp/effect.hpp, include/terminalpp/element.hpp, include/terminalpp/glyph.hpp, include/terminalpp/string.hpp, test/attribute_test.cpp, test/character_set_test.cpp, test/colour_test.cpp, test/effect_test.cpp, test/element_test.cpp, test/glyph_test.cpp, test/string_test.cpp
Strings may now be placed in unordered containers.
Closes #210
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/212)
=> Implemented string hashing

.travis.yml, CMakeLists.txt, conanfile.py
They are now implemented as build requirements.  This means that the tests are
always built (and can be executed), but the requirement isn't passed down the
line to a consumer of the binaries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/219)
=> Removed withTests option from Conan.

.travis.yml
The library was previously picking an older version from an
unmaintained repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/221)
=> Updated nonstd-lite remote in Travis

test/attribute_test.cpp, test/character_set_test.cpp, test/colour_test.cpp, test/control_sequence_test.cpp, test/effect_test.cpp, test/element_test.cpp, test/extent_test.cpp, test/glyph_test.cpp, test/mouse_test.cpp, test/palette_test.cpp, test/point_test.cpp, test/rectangle_test.cpp, test/string_test.cpp, test/virtual_key_test.cpp
This is due to the former being deprecated in favour of the latter
by Google Test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/234)
=> Replaced deprecated INSTANTIATE_TEST_CASE_P macro with INSTANTIATE_TEST_SUITE_P

src/canvas.cpp, src/extent.cpp, src/point.cpp, src/rectangle.cpp
- Added some missing headers, which are necessary to compile with VS2019
- Dereferencing the end() iterator of a container makes VS trigger an assertion. The proposed solution dereferences the begin() iterator (it the container is not empty) and uses pointer arithmetic to make the  end pointer.
- Maybe the name of the template parameter "container" is a bit misleading as this technique works only with vector and string, but not for lists, so "ContinousContainer" could be a better name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/239)
=> Missing headers and fix for end iterator dereferencing

CMakeLists.txt, src/terminal.cpp, test/manip_test.cpp, test/terminal_erase_test.cpp, test/terminal_string_test.cpp, test/terminal_test.hpp
Improves coverage by properly testing the erase_in_display and erase_in_line functions of the terminal class.
Also slightly improved those functions by removing a redundant 0 character from the output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/242)
=> Improve coverage

include/terminalpp/algorithm/for_each_in_region.hpp
It's plausible that for_each_in_region() is called on an object
that yields references to elements, but only has the type forward
declared.  This means that the array access operators fail to
work for the incomplete type.  Therefore, the header must be
included.
Fixes #238
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/243)
=> Added missing include to for_each_in_region.hpp.

CMakeLists.txt
Even when building as a shared library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/250)
=> Terminal++ builds cleanly on MSVC

.github/workflows/build.yml
This should interact properly with gcov-9, which is the version that Github Actions is using.
Fixes #254
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/257)
=> CI Script now downloads lcov 1.15.

include/terminalpp/detail/element_difference.hpp, include/terminalpp/terminal.hpp, test/terminal_erase_test.cpp
This is apparent when changing the screen size on a Windows PuTTY terminal.  Erasing a screen leaves the entire with a background of the currently-set attribute, whereas on an Ubuntu terminal window, this same operation leaves the screen with the default background.
This change applies a change to the default attribute before erasing any part of the screen.
Fixes #264
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/266)
=> Erasing parts of the terminal may leave an attribute trail

src/glyph.cpp, test/glyph_test.cpp
This uncovered a bug that has also been corrected.
Fixes #269.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/270)
=> Re-enabled tests that output unicode glyphs.

include/terminalpp/detail/element_difference.hpp
g++ 5.4 does not recognize these as valid constexpr constants yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/272)
=> Changed some constexpr for const.

CMakeLists.txt, include/terminalpp/detail/element_difference.hpp, include/terminalpp/detail/terminal_reader.hpp, include/terminalpp/glyph.hpp, include/terminalpp/terminal.hpp, src/canvas.cpp
Clang is a little more peculiar about the warnings for unused function
arguments, etc.  Also disabled the tautological compare warning since
it was comparing with a variable that happened to be 0, but that requires
knowledge beyond that which is available to the function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/273)
=> Applied several fixes for Clang 5.

CMakeLists.txt, include/terminalpp/element.hpp, src/detail/element_udl.cpp, test/element_udl_test.cpp
Adds a UDL (_ete = encoded text element) similar to the existing _ets (encoded text string) that performs the same function for a single element.  This resolves the issue where many elements are clumsily created using e.g. "\\U1B87"_ets[0].
Closes #189
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/274)
=> Udl for single elements#189

include/terminalpp/ansi/graphics.hpp, include/terminalpp/colour.hpp, src/colour.cpp, test/colour_test.cpp
Before, they did not take into account the offset into the ANSI colour space, now they do.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/283)
=> Fix high and greyscale colour components.

.gitignore, include/terminalpp/colour.hpp, include/terminalpp/detail/element_difference.hpp, src/colour.cpp, src/detail/element_udl.cpp, test/colour_test.cpp, test/element_test.cpp, test/element_udl_test.cpp, test/encoder_test.cpp, test/string_test.cpp, test/terminal_string_test.cpp
Adds a new colour type: true_colour.
A foreground colour can be built in the UDL from '(' followed by an RGB hexcode (e.g. "\(FF0000Hello!" for a bright red Hello!), and a background colour from ')' followed by an RGB hexcode.
Closes #284
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/285)
=> Add support for True Colour terminals

include/terminalpp/detail/element_difference.hpp, include/terminalpp/terminal.hpp, test/expect_sequence.cpp
This has been marked deprecated in newer versions of fmtlib and
fails to build in Conan because of it.
Fixes #289
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/290)
=> Replaced usages of _format UDL.

conanfile.py, test_package/example.cpp
This was accidentally broken by the changes that picked up generated
version numbers from git.  This change fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kazdragon/terminalpp/293)
=> Fixed ability to create Conan packages.
